#!/bin/bash -e

VERSION="8cc5ce367b5638c4306c2d7cfc652dd099a4643f"

cd docker/mmseqs2
echo Building the Docker image
docker buildx build \
    --platform linux/amd64 \
    -t us-central1-docker.pkg.dev/gcid-bacterial/gcid-bacterial/mmseqs2:$VERSION \
    .
    
echo Pushing to registry
docker push us-central1-docker.pkg.dev/gcid-bacterial/gcid-bacterial/mmseqs2:$VERSION
