version: 1.2
workflows:
 - name: Pilon_Plate_Swipe_Variant_Calling
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_pilon_plate_swipe.wdl
   authors:
    - orcid: 0000-0002-7219-0478
    - name: Marco Teixeira
      email: mcarvalh@broadinstitute.org
   topic: Calls variants in plate swipes with Pilon, given a set of StrainGST results.   
 - name: CleanSweep_Filter
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_cleansweep_filter.wdl
   authors:
    - orcid: 0000-0002-7219-0478
    - name: Marco Teixeira
      email: mcarvalh@broadinstitute.org
   topic: Filter subcommand of CleanSweep. Strain-specific variant calling with plate swipes.
 - name: mGEMS_from_StrainGST
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_mgems.wdl
   authors:
    - orcid: 0000-0002-7219-0478
    - name: Marco Teixeira
      email: mcarvalh@broadinstitute.org
   topic: Calls variants from plate swipe data with mGEMS and Pilon, given a set of StraniGST outputs.