version: 1.2
workflows:
 - name: Pilon_Plate_Swipe_Variant_Calling
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_pilon_plate_swipe.wdl
   authors:
    - orcid: 0000-0002-7219-0478
    - name: Marco Teixeira
      email: mcarvalh@broadinstitute.org
   topic: Calls variants in plate swipes with Pilon, given a set of StrainGST results.   
 - name: CleanSweep_Filter
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_cleansweep_filter.wdl
   authors:
    - orcid: 0000-0002-7219-0478
    - name: Marco Teixeira
      email: mcarvalh@broadinstitute.org
   topic: Filter subcommand of CleanSweep. Strain-specific variant calling with plate swipes.
 - name: mGEMS_from_StrainGST
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_mgems_from_straingst.wdl
   authors:
    - orcid: 0000-0002-7219-0478
    - name: Marco Teixeira
      email: mcarvalh@broadinstitute.org
   topic: Calls variants from plate swipe data with mGEMS and Pilon/Snippy, given a set of StraniGST outputs.
 - name: mGEMS
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_mgems.wdl
   authors:
    - orcid: 0000-0002-7219-0478
    - name: Marco Teixeira
      email: mcarvalh@broadinstitute.org
   topic: Calls variants from plate swipe data with mGEMS and Pilon/Snippy.
 - name: Themisto_index
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_themisto_index.wdl
   authors:
    - orcid: 0000-0002-7219-0478
    - name: Marco Teixeira
      email: mcarvalh@broadinstitute.org
   topic: Builds a Themisto index from a set of FASTA files.
 - name: CleanSweep_VCF_to_Tree
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_cleansweep_vcf_to_tree.wdl
   authors:
    - orcid: 0000-0002-7219-0478
    - name: Marco Teixeira
      email: mcarvalh@broadinstitute.org
   topic: Creates a phylogenetic tree from a set of CleanSweep output VCFs with IQ-TREE2.
 - name: VCF_to_Tree
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_vcf_to_tree.wdl
   authors:
    - orcid: 0000-0002-7219-0478
    - name: Marco Teixeira
      email: mcarvalh@broadinstitute.org
   topic: Builds a Maximum Likelihood tree from a set of VCF files.
 - name: Pilon_Variants
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_pilon_variants.wdl
   authors:
    - orcid: 0000-0002-7219-0478
    - name: Marco Teixeira
      email: mcarvalh@broadinstitute.org
   topic: Calls variants with BWA and Pilon.
 - name: CleanSweep_Variants_to_Full_VCF
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_cleansweep_variants_to_full_vcf.wdl
   authors:
    - orcid: 0000-0002-7219-0478
    - name: Marco Teixeira
      email: mcarvalh@broadinstitute.org
   topic: Given an output VCF file from CleanSweep with only the variant sites and the full VCF file used as input for CleanSweep, creates a CleanSweep output VCF containing all sites in the reference.
 - name: CleanSweep
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_cleansweep.wdl
   authors:
    - orcid: 0000-0002-7219-0478
    - name: Marco Teixeira
      email: mcarvalh@broadinstitute.org
   topic: Pipeline for strain-specific variant calling from plate swipe data with CleanSweep.
 - name: Snippy
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_snippy.wdl
   authors:
    - orcid: 0000-0002-7219-0478
    - name: Marco Teixeira
      email: mcarvalh@broadinstitute.org
   topic: Calls variants with Snippy, supporting contigs as input.
 - name: Bakta
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_bakta.wdl
   authors:
    - orcid: 0000-0002-7219-0478
    - name: Marco Teixeira
      email: mcarvalh@broadinstitute.org
   topic: Bacterial genome annotation with Bakta.
 - name: AMRFinderPlus
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_amrfinderplus.wdl
   authors:
    - orcid: 0000-0002-7219-0478
    - name: Marco Teixeira
      email: mcarvalh@broadinstitute.org
   topic: AMR gene detection with AMRFinderPlus.