version: 1.2
workflows:
 - name: Pilon_Plate_Swipe_Variant_Calling
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_pilon_plate_swipe.wdl
   authors:
    - orcid: 0000-0002-7219-0478
    - name: Marco Teixeira
      email: mcarvalh@broadinstitute.org
   topic: Calls variants in plate swipes with Pilon, given a set of StrainGST results.   
 - name: CleanSweep_Filter
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_cleansweep_filter.wdl
   authors:
    - orcid: 0000-0002-7219-0478
    - name: Marco Teixeira
      email: mcarvalh@broadinstitute.org
   topic: Filter subcommand of CleanSweep. Strain-specific variant calling with plate swipes.
 - name: mGEMS_from_StrainGST
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_mgems_from_straingst.wdl
   authors:
    - orcid: 0000-0002-7219-0478
    - name: Marco Teixeira
      email: mcarvalh@broadinstitute.org
   topic: Calls variants from plate swipe data with mGEMS and Pilon/Snippy, given a set of StraniGST outputs.
 - name: mGEMS
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_mgems.wdl
   authors:
    - orcid: 0000-0002-7219-0478
    - name: Marco Teixeira
      email: mcarvalh@broadinstitute.org
   topic: Calls variants from plate swipe data with mGEMS and Pilon/Snippy.
 - name: Themisto_index
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_themisto_index.wdl
   authors:
    - orcid: 0000-0002-7219-0478
    - name: Marco Teixeira
      email: mcarvalh@broadinstitute.org
   topic: Builds a Themisto index from a set of FASTA files.
 - name: CleanSweep_VCF_to_Tree
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_cleansweep_vcf_to_tree.wdl
   authors:
    - orcid: 0000-0002-7219-0478
    - name: Marco Teixeira
      email: mcarvalh@broadinstitute.org
   topic: Creates a phylogenetic tree from a set of CleanSweep output VCFs with IQ-TREE2.
 - name: VCF_to_Tree
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_vcf_to_tree.wdl
   authors:
    - orcid: 0000-0002-7219-0478
    - name: Marco Teixeira
      email: mcarvalh@broadinstitute.org
   topic: Builds a Maximum Likelihood tree from a set of VCF files.
 - name: Pilon_Variants
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_pilon_variants.wdl
   authors:
    - orcid: 0000-0002-7219-0478
    - name: Marco Teixeira
      email: mcarvalh@broadinstitute.org
   topic: Calls variants with BWA and Pilon.