#!/bin/bash -e

VERSION="1.3.3"

cd docker/mgems
echo Building the Docker image
docker build -t us-central1-docker.pkg.dev/gcid-bacterial/gcid-bacterial/mgems:$VERSION .
echo Pushing to Docker Hub
docker push us-central1-docker.pkg.dev/gcid-bacterial/gcid-bacterial/mgems:$VERSION