#!/bin/bash -e

VERSION="1.0.1"
IMG_NAME="plasmaag"

img_path="us-central1-docker.pkg.dev/gcid-bacterial/gcid-bacterial/$IMG_NAME:$VERSION"

cd docker/plasmaag
echo Building the Docker image
docker buildx build \
    --platform linux/amd64 \
    -t $img_path \
    .
    
echo Pushing to registry
docker push $img_path